[ADD] Description  of each function
iTeam-S/Ampalibe pull request #6
Opened 2022-02-21 19:28 UTC by rivo2302

2022-02-21 19:43 UTC, rootkit7628 requested changes
Look at those feedback, please. You can still improve those docstring.

2022-02-21 19:43 UTC, rootkit7628 commented on ampalibe/requete.py
> +            The function that checks if the database
Ce n'est pas un simple fonction, il faut peut être précisé que c'est un décorateur

2022-02-21 19:43 UTC, rootkit7628 commented on ampalibe/requete.py
> +            Get action user
`Get user's action` je pense

2022-02-21 19:43 UTC, rootkit7628 commented on ampalibe/requete.py
> +            Define aciton of an user
`a user`

2022-02-21 19:43 UTC, rootkit7628 commented on ampalibe/requete.py
> +            Get temp parameter of an user
C'est un doc alors n'abrège pas les mots `temporary`

2022-02-21 19:43 UTC, rootkit7628 commented on ampalibe/requete.py
> +            Insert or set a temp parameter of an user
même remarque pour `temp`

2022-02-21 20:13 UTC, gaetan1903 commented on ampalibe/requete.py
> +            The function that checks if the database
Right

2022-02-21 20:18 UTC, gaetan1903 commented on ampalibe/requete.py
> +            The function that checks if the database
D'accord avec@rootkit7628

2022-02-24 18:19 UTC, gaetan1903 commented on ampalibe/utils.py
> +    This decorator returns the list of functions that the bot must process.
it inserts all function in a list object, not return the list

2022-02-24 18:19 UTC, gaetan1903 commented on ampalibe/utils.py
> +    This decorator returns the list of functions that the bot must process.
same thing as command function

2022-02-24 19:08 UTC, rootkit7628 requested changes

2022-02-24 19:08 UTC, rootkit7628 commented on ampalibe/utils.py
> +    A function that will  take as parameter the object payload and as output a string .
I think more explain what the function does. not just mentioning parameter and output.
Something more like :  `Function to convert payload object to a string version`
To specify parameter & return : 
```
    :param payload : <description>
    :return  payload : <description>
```

2022-02-25 09:54 UTC, gaetan1903 approved these changes
J'ai fait les modifs nécessaires et j'approuve now

2022-02-25 10:46 UTC, merged